const data=[
    {
        "id":101,
        "name":"Karna",
        "age":25
    },
    {
        "id":102,
        "name":"Dharma",
        "age":25
    },
    {
        "id":103,
        "name":"Bheema",
        "age":25
    },
    {
        "id":104,
        "name":"Arjuna",
        "age":25
    },
    {
        "id":105,
        "name":"Nakula",
        "age":25
    },
    {
        "id":106,
        "name":"Sahadev",
        "age":25
    },
    {
        "id":107,
        "name":"Duryodhana",
        "age":25
    },
    {
        "id":108,
        "name":"Dhusyasana",
        "age":25
    }
];
export function getData(){
    return data;
}